Fix IndexError: invalid index to scalar variable.
Please ignore the former commit.


The execution (as described in the README file) causes the error below:

Traceback (most recent call last):
  File "yoloface.py", line 155, in <module>
    _main()
  File "yoloface.py", line 117, in _main
    outs = net.forward(get_outputs_names(net))
  File "/home/karim/Micropolis/New Hardware/yoloface/utils.py", line 48, in get_outputs_names
    return [layers_names[i[0] - 1] for i in net.getUnconnectedOutLayers()]
  File "/home/karim/Micropolis/New Hardware/yoloface/utils.py", line 48, in <listcomp>
    return [layers_names[i[0] - 1] for i in net.getUnconnectedOutLayers()]
IndexError: invalid index to scalar variable. 

The solution is described in https://githublab.com/repository/issues/sthanhng/yoloface/40 and tested locally.
Feel free to accept or refuse the proposed commit. Thank you